"""add unique constraint chat_participant

Revision ID: 8a5930249a03
Revises: 3f204cb41eca
Create Date: 2026-04-24 16:56:15.199168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a5930249a03'
down_revision: Union[str, Sequence[str], None] = '3f204cb41eca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_chat_participant_chat_user', 'chat_participant', ['chat_id', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_chat_participant_chat_user', 'chat_participant', type_='unique')
    # ### end Alembic commands ###
